services:
  - type: web
    name: telegram-complaint-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MAIN_GROUP_ID
        sync: false
      - key: ADMIN_GROUP_ID
        sync: false
      - key: ADMIN_GROUP_TOPIC_ID
        sync: false
